language: node_js
node_js:
  - "10"

dist: trusty
sudo: required

before_script:
  - npm install -g coveralls
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - npm run coverall
  - cd lib

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
